# Generated by Django 5.2.5 on 2025-08-25 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_pays'),
    ]

    operations = [
        migrations.AddField(
            model_name='pays',
            name='payment_urls',
            field=models.URLField(blank=True, null=True, verbose_name='Cсылка на платеж'),
        ),
    ]
