# Generated by Django 5.2.5 on 2025-08-25 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_pays_payment_urls'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pays',
            name='payment_urls',
            field=models.URLField(blank=True, max_length=1000, null=True, verbose_name='Cсылка на платеж'),
        ),
    ]
