# Generated by Django 5.2.5 on 2025-08-25 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_pays_payment_urls'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pays',
            name='summ_pays',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Сумма оплаты'),
        ),
    ]
