# Generated by Django 5.2.5 on 2025-08-27 14:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_pays_summ_pays'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='last_login',
            field=models.DateTimeField(auto_now=True, default=datetime.datetime(2025, 8, 27, 14, 20, 42, 310478, tzinfo=datetime.timezone.utc), verbose_name='Последняя активность'),
            preserve_default=False,
        ),
    ]
