# Generated by Django 5.2.5 on 2025-09-03 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название курса')),
                ('image', models.ImageField(blank=True, null=True, upload_to='materials/avatar', verbose_name='AVATAR')),
                ('description', models.TextField(blank=True, help_text='Введите описание', verbose_name='Описание курса')),
                ('price', models.DecimalField(decimal_places=2, default=100, max_digits=10, verbose_name='Цена')),
            ],
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название урока')),
                ('preview', models.ImageField(blank=True, null=True, upload_to='materials/avatar', verbose_name='AVATAR')),
                ('description', models.TextField(blank=True, help_text='Введите описание', verbose_name='Описание урока')),
                ('link_video', models.URLField(blank=True, help_text='Ведите ссылку', null=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Подписка',
                'verbose_name_plural': 'Подписки',
            },
        ),
    ]
